### ISSUE TITLE
Paytm Project particular slide not rendering and throwing error in the console.

### ISSUE THREAD

**Issue by Rahulsoni9321** [code100x/daily-code#279]
**Describe the bug**
I was going through the notes of Paytm project 2nd part (recent one) and at a Particular slide it throws an error on the screen and shows some error in the console screenshot attached below.

![Screenshot 2024-04-16 003159](https://github.com/code100x/daily-code/assets/98963266/f8227346-b94f-4f59-a217-582a54d51467)

**Comment by sandeepky47** [comment]
The error is because of no/zero content in 2nd code block hence the **properties.title** field is null/undefined and accessing title[0] array element throw "cannot read properties of undefined". Below fix I tried locally and working fine. Will raise PR soon or we can get rid of this empty code block.
@hkirat 
<img width="1045" alt="Screenshot 2024-04-16 at 9 22 19 AM" src="https://github.com/code100x/daily-code/assets/71933029/05c8a325-4649-4725-a389-e0518f84d8d2">
<img width="840" alt="Screenshot 2024-04-16 at 9 21 49 AM" src="https://github.com/code100x/daily-code/assets/71933029/fad564bc-79be-4ea6-bab8-6707eef3f42d">
<img width="681" alt="image" src="https://github.com/code100x/daily-code/assets/71933029/bf0c5770-105a-4369-9cb6-082a1c361ed4">

**Comment by sandeepky47** [comment]
Above issue will be fixed by this [PR](https://github.com/code100x/daily-code/pull/282)
