### ISSUE TITLE
feature: Add a duplicating option for slides, so that it direclty creates a copy of the slides in notion.

### ISSUE THREAD

**Issue by ajaykasturi** [code100x/daily-code#442]
Problem:
When downloading the slides from dailcode, some part of the code  is clipping.

Solution:
Adding a feature, which duplicates the slides direclty into notion site, so that the notes persist in user's notion account.

How To Add:
Open the below notes link, you will find out the duplicating option built by notion, add the same option to slides on dailycode.
https://quickest-juniper-f9c.notion.site/Cohort-2-0-FullStack-Open-Source-6b6c2a9f1282499aba4782b88bf7e204

https://github.com/code100x/daily-code/assets/52690028/05cc7389-bf87-46b2-b29d-64c0672003b6

**Comment by ayesparshh** [comment]
![Screenshot 2024-05-20 145619](https://github.com/code100x/daily-code/assets/96340685/c8722638-08e0-4b04-a95b-92d8a4fabafe)
sorry for offtopic question
im getting this error after running the repo please help, not able to run the code due to this error

**Comment by ayesparshh** [comment]
after running this command chmod +x ./setupDB.sh
./setupDB.sh

**Comment by hxdy-1** [comment]
@ayesparshh have installed all the dependencies?
Just follow the set-up steps in readme...

**Comment by ayesparshh** [comment]
yes after yarn install, cd packages/db then chmod +x ./setupDB.sh
./setupDB.sh ,this command doesn't work on migrating the db, but successfully start a container

**Comment by t007rushi** [comment]
@ajaykasturi so the feature would be like the `duplicate to notion` option right next to the Download button?
And after click it copies all slides into user's notion doc?

**Comment by ajaykasturi** [comment]
> @ajaykasturi so the feature would be like the `duplicate to notion` option right next to the Download button? And after click it copies all slides into user's notion doc?

Yes

**Comment by rahmatdeep** [comment]
have to link with the notion account then also somehow

**Comment by ayesparshh** [comment]
@ajaykasturi  https://quickest-juniper-f9c.notion.site/Cohort-2-0-FullStack-Open-Source-6b6c2a9f1282499aba4782b88bf7e204 
 In this example the Notion documents are only available for viewing and are not saved to personal accounts. To make the documents available in personal accounts, you first need to create a master account where all the slides are uploaded. From there, you can use Notion's "Duplicate" feature to allow users to copy the slides into their own accounts. If you are aware of any alternative methods, please share them. Otherwise, I will proceed with this implementation.
